services:
  feedback-postgres:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2000M
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

    image: "postgres:17.6-bookworm"
    container_name: feedback-postgres--development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
      POSTGRES_PORT: 5432
      DATA_PATH: ./data
      LC_LANG: ru_RU.UTF-8
    volumes:
      - ./data-development:/var/lib/postgresql/data

  feedback-pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - feedback-postgres
    container_name: feedback-pgadmin--development
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword