services:
  feedback-postgres:
    # image: "postgres:17.6-bookworm"
    build:
      context: .
    container_name: feedback-postgres--production
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: feedback
      POSTGRES_PORT: 5432
      PGUSER_FILE: /run/secrets/postgres_user
      DATA_PATH: ./data
      LOGS_PATH: ./logs
      WALG_LIBSODIUM_KEY: 366e6507d61c1c2aaf9fe1bc2abba8be85ce114122758eeba9938233862677fb
      WALG_AUTOMATED_BACKUPS: true
      WALG_RETENTION_DAYS: 30
      AWS_ACCESS_KEY_ID: /run/secrets/minio_access_key
      AWS_SECRET_ACCESS_KEY: /run/secrets/minio_secret_key
      AWS_ENDPOINT: https://minio.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai
      WALG_S3_PREFIX: s3://backup/pg
      LC_LANG: ru_RU.UTF-8
    secrets:
      - postgres_user
      - postgres_password
      - minio_access_key
      - minio_secret_key
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2000M
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/wal-g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d feedback -U `cat $$POSTGRES_USER_FILE`"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feedback-pgadmin--production
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: info@example.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_default_password
      # PGADMIN_ENABLE_TLS: true
    secrets:
      - pgadmin_default_email
      - pgadmin_default_password
    ports:
      - "5050:80"
    depends_on:
      - feedback-postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)"
      - "traefik.http.routers.pgadmin.middlewares=chain-authelia@file"
      - "traefik.http.routers.pgadmin.tls=true"
      - "traefik.http.routers.pgadmin.tls.certresolver=tlsresolver"
    tty: true

secrets:
  pgadmin_default_email:
    file: ../secrets/pgadmin_default_email
  pgadmin_default_password:
    file: ../secrets/pgadmin_default_password
  postgres_user:
    file: ../secrets/postgres_user
  postgres_password:
    file: ../secrets/postgres_password
  # minio_access_key:
  #   external: true
  # minio_secret_key:
  #   external: true
