services:
  postgres:
    image: "postgres:17.6-bookworm"
    build:
      context: .
    container_name: feedback-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
      POSTGRES_PORT: 5432
      DATA_PATH: ./data
      LOGS_PATH: ./logs
      WALG_AUTOMATED_BACKUPS: true
      WALG_RETENTION_DAYS: 30
      WALG_LIBSODIUM_KEY: 11ff11dd11ff1111ecedd0e11111cb4ea1d3f975f4211db40611348ae8e437af
      AWS_ACCESS_KEY_ID: mostsecretminiokey
      AWS_SECRET_ACCESS_KEY: mostsecretminiokey
      AWS_ENDPOINT: https://minio.localhost
      WALG_S3_PREFIX: s3://backup/postgres-backups
      LC_LANG: ru_RU.UTF-8
    deploy:
      resources:
        limits:
          memory: 2000M
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/wal-g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres} -d ${POSTGRES_DB-feedback}"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: feedback-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      # - "traefik.http.routers.pgadmin.middlewares=chain-authelia@file"
      - "traefik.http.routers.pgadmin.tls=true"
