services:
  feedback-postgres:
    extends:
      file: compose.postgres.development.yaml
      service: feedback-postgres

    image: feedback-postgres-staging
    build:
      context: .
    container_name: feedback-postgres--staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedback
      POSTGRES_PORT: 5432
      DATA_PATH: ./data
      LOGS_PATH: ./logs
      WALG_AUTOMATED_BACKUPS: true
      WALG_RETENTION_DAYS: 30
      WALG_LIBSODIUM_KEY: 366e6507d61c1c2aaf9fe1bc2abba8be85ce114122758eeba9938233862677fb
      AWS_ACCESS_KEY_ID: mostsecretminiokey
      AWS_SECRET_ACCESS_KEY: mostsecretminiokey
      AWS_ENDPOINT: https://minio.localhost
      WALG_S3_PREFIX: s3://backup/pg
      LC_LANG: ru_RU.UTF-8
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/wal-g

  feedback-pgadmin:
    extends:
      file: compose.postgres.development.yaml
      service: feedback-pgadmin

    container_name: feedback-pgadmin--staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.routers.pgadmin.tls=true"
      # - "traefik.http.routers.pgadmin.middlewares=chain-authelia@file"
