/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedVoting_votesRouteImport } from './routes/_authenticated/voting_votes'
import { Route as AuthenticatedVoting_unitsRouteImport } from './routes/_authenticated/voting_units'
import { Route as AuthenticatedTopic_category_topicsRouteImport } from './routes/_authenticated/topic_category_topics'
import { Route as AuthenticatedOfficialsRouteImport } from './routes/_authenticated/officials'
import { Route as AuthenticatedCitizensRouteImport } from './routes/_authenticated/citizens'
import { Route as AuthenticatedAdministrative_unitsRouteImport } from './routes/_authenticated/administrative_units'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects.create'
import { Route as AuthenticatedProjectsShowIdRouteImport } from './routes/_authenticated/projects.$showId'
import { Route as AuthenticatedFeedbackShowIdRouteImport } from './routes/_authenticated/feedback.$showId'
import { Route as AuthenticatedProjectsEditIdEditRouteImport } from './routes/_authenticated/projects.$editId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoting_votesRoute =
  AuthenticatedVoting_votesRouteImport.update({
    id: '/voting_votes',
    path: '/voting_votes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVoting_unitsRoute =
  AuthenticatedVoting_unitsRouteImport.update({
    id: '/voting_units',
    path: '/voting_units',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopic_category_topicsRoute =
  AuthenticatedTopic_category_topicsRouteImport.update({
    id: '/topic_category_topics',
    path: '/topic_category_topics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficialsRoute = AuthenticatedOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCitizensRoute = AuthenticatedCitizensRouteImport.update({
  id: '/citizens',
  path: '/citizens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministrative_unitsRoute =
  AuthenticatedAdministrative_unitsRouteImport.update({
    id: '/administrative_units',
    path: '/administrative_units',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsShowIdRoute =
  AuthenticatedProjectsShowIdRouteImport.update({
    id: '/projects/$showId',
    path: '/projects/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackShowIdRoute =
  AuthenticatedFeedbackShowIdRouteImport.update({
    id: '/feedback/$showId',
    path: '/feedback/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsEditIdEditRoute =
  AuthenticatedProjectsEditIdEditRouteImport.update({
    id: '/projects/$editId/edit',
    path: '/projects/$editId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrative_units': typeof AuthenticatedAdministrative_unitsRoute
  '/citizens': typeof AuthenticatedCitizensRoute
  '/officials': typeof AuthenticatedOfficialsRoute
  '/topic_category_topics': typeof AuthenticatedTopic_category_topicsRoute
  '/voting_units': typeof AuthenticatedVoting_unitsRoute
  '/voting_votes': typeof AuthenticatedVoting_votesRoute
  '/login': typeof LoginIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrative_units': typeof AuthenticatedAdministrative_unitsRoute
  '/citizens': typeof AuthenticatedCitizensRoute
  '/officials': typeof AuthenticatedOfficialsRoute
  '/topic_category_topics': typeof AuthenticatedTopic_category_topicsRoute
  '/voting_units': typeof AuthenticatedVoting_unitsRoute
  '/voting_votes': typeof AuthenticatedVoting_votesRoute
  '/login': typeof LoginIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/administrative_units': typeof AuthenticatedAdministrative_unitsRoute
  '/_authenticated/citizens': typeof AuthenticatedCitizensRoute
  '/_authenticated/officials': typeof AuthenticatedOfficialsRoute
  '/_authenticated/topic_category_topics': typeof AuthenticatedTopic_category_topicsRoute
  '/_authenticated/voting_units': typeof AuthenticatedVoting_unitsRoute
  '/_authenticated/voting_votes': typeof AuthenticatedVoting_votesRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/_authenticated/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrative_units'
    | '/citizens'
    | '/officials'
    | '/topic_category_topics'
    | '/voting_units'
    | '/voting_votes'
    | '/login'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/feedback'
    | '/projects'
    | '/projects/$editId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrative_units'
    | '/citizens'
    | '/officials'
    | '/topic_category_topics'
    | '/voting_units'
    | '/voting_votes'
    | '/login'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/feedback'
    | '/projects'
    | '/projects/$editId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/administrative_units'
    | '/_authenticated/citizens'
    | '/_authenticated/officials'
    | '/_authenticated/topic_category_topics'
    | '/_authenticated/voting_units'
    | '/_authenticated/voting_votes'
    | '/login/'
    | '/_authenticated/feedback/$showId'
    | '/_authenticated/projects/$showId'
    | '/_authenticated/projects/create'
    | '/_authenticated/feedback/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$editId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voting_votes': {
      id: '/_authenticated/voting_votes'
      path: '/voting_votes'
      fullPath: '/voting_votes'
      preLoaderRoute: typeof AuthenticatedVoting_votesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/voting_units': {
      id: '/_authenticated/voting_units'
      path: '/voting_units'
      fullPath: '/voting_units'
      preLoaderRoute: typeof AuthenticatedVoting_unitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic_category_topics': {
      id: '/_authenticated/topic_category_topics'
      path: '/topic_category_topics'
      fullPath: '/topic_category_topics'
      preLoaderRoute: typeof AuthenticatedTopic_category_topicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officials': {
      id: '/_authenticated/officials'
      path: '/officials'
      fullPath: '/officials'
      preLoaderRoute: typeof AuthenticatedOfficialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizens': {
      id: '/_authenticated/citizens'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof AuthenticatedCitizensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrative_units': {
      id: '/_authenticated/administrative_units'
      path: '/administrative_units'
      fullPath: '/administrative_units'
      preLoaderRoute: typeof AuthenticatedAdministrative_unitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$showId': {
      id: '/_authenticated/projects/$showId'
      path: '/projects/$showId'
      fullPath: '/projects/$showId'
      preLoaderRoute: typeof AuthenticatedProjectsShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/$showId': {
      id: '/_authenticated/feedback/$showId'
      path: '/feedback/$showId'
      fullPath: '/feedback/$showId'
      preLoaderRoute: typeof AuthenticatedFeedbackShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$editId/edit': {
      id: '/_authenticated/projects/$editId/edit'
      path: '/projects/$editId/edit'
      fullPath: '/projects/$editId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsEditIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdministrative_unitsRoute: typeof AuthenticatedAdministrative_unitsRoute
  AuthenticatedCitizensRoute: typeof AuthenticatedCitizensRoute
  AuthenticatedOfficialsRoute: typeof AuthenticatedOfficialsRoute
  AuthenticatedTopic_category_topicsRoute: typeof AuthenticatedTopic_category_topicsRoute
  AuthenticatedVoting_unitsRoute: typeof AuthenticatedVoting_unitsRoute
  AuthenticatedVoting_votesRoute: typeof AuthenticatedVoting_votesRoute
  AuthenticatedFeedbackShowIdRoute: typeof AuthenticatedFeedbackShowIdRoute
  AuthenticatedProjectsShowIdRoute: typeof AuthenticatedProjectsShowIdRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsEditIdEditRoute: typeof AuthenticatedProjectsEditIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministrative_unitsRoute:
    AuthenticatedAdministrative_unitsRoute,
  AuthenticatedCitizensRoute: AuthenticatedCitizensRoute,
  AuthenticatedOfficialsRoute: AuthenticatedOfficialsRoute,
  AuthenticatedTopic_category_topicsRoute:
    AuthenticatedTopic_category_topicsRoute,
  AuthenticatedVoting_unitsRoute: AuthenticatedVoting_unitsRoute,
  AuthenticatedVoting_votesRoute: AuthenticatedVoting_votesRoute,
  AuthenticatedFeedbackShowIdRoute: AuthenticatedFeedbackShowIdRoute,
  AuthenticatedProjectsShowIdRoute: AuthenticatedProjectsShowIdRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsEditIdEditRoute: AuthenticatedProjectsEditIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
