/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedOfficialsRouteImport } from './routes/_authenticated/officials'
import { Route as AuthenticatedVoting_votesIndexRouteImport } from './routes/_authenticated/voting_votes/index'
import { Route as AuthenticatedVoting_unitsIndexRouteImport } from './routes/_authenticated/voting_units/index'
import { Route as AuthenticatedTopic_category_topicsIndexRouteImport } from './routes/_authenticated/topic_category_topics/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedCitizensIndexRouteImport } from './routes/_authenticated/citizens/index'
import { Route as AuthenticatedAdministrative_unitsIndexRouteImport } from './routes/_authenticated/administrative_units/index'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedProjectsShowIdRouteImport } from './routes/_authenticated/projects/$showId'
import { Route as AuthenticatedFeedbackShowIdRouteImport } from './routes/_authenticated/feedback.$showId'
import { Route as AuthenticatedProjectsEditIdEditRouteImport } from './routes/_authenticated/projects/$editId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficialsRoute = AuthenticatedOfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVoting_votesIndexRoute =
  AuthenticatedVoting_votesIndexRouteImport.update({
    id: '/voting_votes/',
    path: '/voting_votes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVoting_unitsIndexRoute =
  AuthenticatedVoting_unitsIndexRouteImport.update({
    id: '/voting_units/',
    path: '/voting_units/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTopic_category_topicsIndexRoute =
  AuthenticatedTopic_category_topicsIndexRouteImport.update({
    id: '/topic_category_topics/',
    path: '/topic_category_topics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitizensIndexRoute =
  AuthenticatedCitizensIndexRouteImport.update({
    id: '/citizens/',
    path: '/citizens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministrative_unitsIndexRoute =
  AuthenticatedAdministrative_unitsIndexRouteImport.update({
    id: '/administrative_units/',
    path: '/administrative_units/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsShowIdRoute =
  AuthenticatedProjectsShowIdRouteImport.update({
    id: '/projects/$showId',
    path: '/projects/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackShowIdRoute =
  AuthenticatedFeedbackShowIdRouteImport.update({
    id: '/feedback/$showId',
    path: '/feedback/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsEditIdEditRoute =
  AuthenticatedProjectsEditIdEditRouteImport.update({
    id: '/projects/$editId/edit',
    path: '/projects/$editId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/officials': typeof AuthenticatedOfficialsRoute
  '/login': typeof LoginIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/administrative_units': typeof AuthenticatedAdministrative_unitsIndexRoute
  '/citizens': typeof AuthenticatedCitizensIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/topic_category_topics': typeof AuthenticatedTopic_category_topicsIndexRoute
  '/voting_units': typeof AuthenticatedVoting_unitsIndexRoute
  '/voting_votes': typeof AuthenticatedVoting_votesIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/officials': typeof AuthenticatedOfficialsRoute
  '/login': typeof LoginIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/administrative_units': typeof AuthenticatedAdministrative_unitsIndexRoute
  '/citizens': typeof AuthenticatedCitizensIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/topic_category_topics': typeof AuthenticatedTopic_category_topicsIndexRoute
  '/voting_units': typeof AuthenticatedVoting_unitsIndexRoute
  '/voting_votes': typeof AuthenticatedVoting_votesIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/officials': typeof AuthenticatedOfficialsRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/_authenticated/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/administrative_units/': typeof AuthenticatedAdministrative_unitsIndexRoute
  '/_authenticated/citizens/': typeof AuthenticatedCitizensIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/topic_category_topics/': typeof AuthenticatedTopic_category_topicsIndexRoute
  '/_authenticated/voting_units/': typeof AuthenticatedVoting_unitsIndexRoute
  '/_authenticated/voting_votes/': typeof AuthenticatedVoting_votesIndexRoute
  '/_authenticated/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/officials'
    | '/login'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/administrative_units'
    | '/citizens'
    | '/feedback'
    | '/projects'
    | '/topic_category_topics'
    | '/voting_units'
    | '/voting_votes'
    | '/projects/$editId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/officials'
    | '/login'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/administrative_units'
    | '/citizens'
    | '/feedback'
    | '/projects'
    | '/topic_category_topics'
    | '/voting_units'
    | '/voting_votes'
    | '/projects/$editId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/officials'
    | '/login/'
    | '/_authenticated/feedback/$showId'
    | '/_authenticated/projects/$showId'
    | '/_authenticated/projects/create'
    | '/_authenticated/administrative_units/'
    | '/_authenticated/citizens/'
    | '/_authenticated/feedback/'
    | '/_authenticated/projects/'
    | '/_authenticated/topic_category_topics/'
    | '/_authenticated/voting_units/'
    | '/_authenticated/voting_votes/'
    | '/_authenticated/projects/$editId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/officials': {
      id: '/_authenticated/officials'
      path: '/officials'
      fullPath: '/officials'
      preLoaderRoute: typeof AuthenticatedOfficialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/voting_votes/': {
      id: '/_authenticated/voting_votes/'
      path: '/voting_votes'
      fullPath: '/voting_votes'
      preLoaderRoute: typeof AuthenticatedVoting_votesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/voting_units/': {
      id: '/_authenticated/voting_units/'
      path: '/voting_units'
      fullPath: '/voting_units'
      preLoaderRoute: typeof AuthenticatedVoting_unitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic_category_topics/': {
      id: '/_authenticated/topic_category_topics/'
      path: '/topic_category_topics'
      fullPath: '/topic_category_topics'
      preLoaderRoute: typeof AuthenticatedTopic_category_topicsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizens/': {
      id: '/_authenticated/citizens/'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof AuthenticatedCitizensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administrative_units/': {
      id: '/_authenticated/administrative_units/'
      path: '/administrative_units'
      fullPath: '/administrative_units'
      preLoaderRoute: typeof AuthenticatedAdministrative_unitsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$showId': {
      id: '/_authenticated/projects/$showId'
      path: '/projects/$showId'
      fullPath: '/projects/$showId'
      preLoaderRoute: typeof AuthenticatedProjectsShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/$showId': {
      id: '/_authenticated/feedback/$showId'
      path: '/feedback/$showId'
      fullPath: '/feedback/$showId'
      preLoaderRoute: typeof AuthenticatedFeedbackShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$editId/edit': {
      id: '/_authenticated/projects/$editId/edit'
      path: '/projects/$editId/edit'
      fullPath: '/projects/$editId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsEditIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOfficialsRoute: typeof AuthenticatedOfficialsRoute
  AuthenticatedFeedbackShowIdRoute: typeof AuthenticatedFeedbackShowIdRoute
  AuthenticatedProjectsShowIdRoute: typeof AuthenticatedProjectsShowIdRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedAdministrative_unitsIndexRoute: typeof AuthenticatedAdministrative_unitsIndexRoute
  AuthenticatedCitizensIndexRoute: typeof AuthenticatedCitizensIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedTopic_category_topicsIndexRoute: typeof AuthenticatedTopic_category_topicsIndexRoute
  AuthenticatedVoting_unitsIndexRoute: typeof AuthenticatedVoting_unitsIndexRoute
  AuthenticatedVoting_votesIndexRoute: typeof AuthenticatedVoting_votesIndexRoute
  AuthenticatedProjectsEditIdEditRoute: typeof AuthenticatedProjectsEditIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOfficialsRoute: AuthenticatedOfficialsRoute,
  AuthenticatedFeedbackShowIdRoute: AuthenticatedFeedbackShowIdRoute,
  AuthenticatedProjectsShowIdRoute: AuthenticatedProjectsShowIdRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedAdministrative_unitsIndexRoute:
    AuthenticatedAdministrative_unitsIndexRoute,
  AuthenticatedCitizensIndexRoute: AuthenticatedCitizensIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedTopic_category_topicsIndexRoute:
    AuthenticatedTopic_category_topicsIndexRoute,
  AuthenticatedVoting_unitsIndexRoute: AuthenticatedVoting_unitsIndexRoute,
  AuthenticatedVoting_votesIndexRoute: AuthenticatedVoting_votesIndexRoute,
  AuthenticatedProjectsEditIdEditRoute: AuthenticatedProjectsEditIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
