/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedOfficialsIndexRouteImport } from './routes/_authenticated/officials/index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback/index'
import { Route as AuthenticatedCitizensIndexRouteImport } from './routes/_authenticated/citizens/index'
import { Route as AuthenticatedProjectsCreateRouteImport } from './routes/_authenticated/projects/create'
import { Route as AuthenticatedProjectsShowIdRouteImport } from './routes/_authenticated/projects/$showId'
import { Route as AuthenticatedFeedbackShowIdRouteImport } from './routes/_authenticated/feedback/$showId'
import { Route as AuthenticatedProjectsEditIdEditRouteImport } from './routes/_authenticated/projects/$editId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfficialsIndexRoute =
  AuthenticatedOfficialsIndexRouteImport.update({
    id: '/officials/',
    path: '/officials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitizensIndexRoute =
  AuthenticatedCitizensIndexRouteImport.update({
    id: '/citizens/',
    path: '/citizens/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsCreateRoute =
  AuthenticatedProjectsCreateRouteImport.update({
    id: '/projects/create',
    path: '/projects/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsShowIdRoute =
  AuthenticatedProjectsShowIdRouteImport.update({
    id: '/projects/$showId',
    path: '/projects/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedbackShowIdRoute =
  AuthenticatedFeedbackShowIdRouteImport.update({
    id: '/feedback/$showId',
    path: '/feedback/$showId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsEditIdEditRoute =
  AuthenticatedProjectsEditIdEditRouteImport.update({
    id: '/projects/$editId/edit',
    path: '/projects/$editId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/citizens': typeof AuthenticatedCitizensIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/officials': typeof AuthenticatedOfficialsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthIndexRoute
  '/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/citizens': typeof AuthenticatedCitizensIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/officials': typeof AuthenticatedOfficialsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/feedback/$showId': typeof AuthenticatedFeedbackShowIdRoute
  '/_authenticated/projects/$showId': typeof AuthenticatedProjectsShowIdRoute
  '/_authenticated/projects/create': typeof AuthenticatedProjectsCreateRoute
  '/_authenticated/citizens/': typeof AuthenticatedCitizensIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/officials/': typeof AuthenticatedOfficialsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$editId/edit': typeof AuthenticatedProjectsEditIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/citizens'
    | '/feedback'
    | '/officials'
    | '/projects'
    | '/projects/$editId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/feedback/$showId'
    | '/projects/$showId'
    | '/projects/create'
    | '/citizens'
    | '/feedback'
    | '/officials'
    | '/projects'
    | '/projects/$editId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth/'
    | '/_authenticated/feedback/$showId'
    | '/_authenticated/projects/$showId'
    | '/_authenticated/projects/create'
    | '/_authenticated/citizens/'
    | '/_authenticated/feedback/'
    | '/_authenticated/officials/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$editId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/officials/': {
      id: '/_authenticated/officials/'
      path: '/officials'
      fullPath: '/officials'
      preLoaderRoute: typeof AuthenticatedOfficialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/citizens/': {
      id: '/_authenticated/citizens/'
      path: '/citizens'
      fullPath: '/citizens'
      preLoaderRoute: typeof AuthenticatedCitizensIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/create': {
      id: '/_authenticated/projects/create'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AuthenticatedProjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$showId': {
      id: '/_authenticated/projects/$showId'
      path: '/projects/$showId'
      fullPath: '/projects/$showId'
      preLoaderRoute: typeof AuthenticatedProjectsShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback/$showId': {
      id: '/_authenticated/feedback/$showId'
      path: '/feedback/$showId'
      fullPath: '/feedback/$showId'
      preLoaderRoute: typeof AuthenticatedFeedbackShowIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$editId/edit': {
      id: '/_authenticated/projects/$editId/edit'
      path: '/projects/$editId/edit'
      fullPath: '/projects/$editId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsEditIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFeedbackShowIdRoute: typeof AuthenticatedFeedbackShowIdRoute
  AuthenticatedProjectsShowIdRoute: typeof AuthenticatedProjectsShowIdRoute
  AuthenticatedProjectsCreateRoute: typeof AuthenticatedProjectsCreateRoute
  AuthenticatedCitizensIndexRoute: typeof AuthenticatedCitizensIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedOfficialsIndexRoute: typeof AuthenticatedOfficialsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsEditIdEditRoute: typeof AuthenticatedProjectsEditIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFeedbackShowIdRoute: AuthenticatedFeedbackShowIdRoute,
  AuthenticatedProjectsShowIdRoute: AuthenticatedProjectsShowIdRoute,
  AuthenticatedProjectsCreateRoute: AuthenticatedProjectsCreateRoute,
  AuthenticatedCitizensIndexRoute: AuthenticatedCitizensIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedOfficialsIndexRoute: AuthenticatedOfficialsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsEditIdEditRoute: AuthenticatedProjectsEditIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
