services:
  feedback-bullboard:
    container_name: feedback-bullboard--development
    image: venatum/bull-board
    restart: unless-stopped
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
    environment:
      REDIS_HOST: feedback-redis
      REDIS_DB: 0
      REDIS_USE_TLS: false
      REDIS_PASSWORD: mostsecretpassword
    depends_on:
      - feedback-redis
