services:
  feedback-bullboard:
    extends:
      file: compose.bullboard.development.yaml
      service: feedback-bullboard
    container_name: feedback-bullboard--production
    labels:
      - traefik.enable=true
      - traefik.http.routers.bullboard.entrypoints=web-secure
      - traefik.http.routers.bullboard.rule=Host(`bullboard.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)
      - traefik.http.routers.bullboard.middlewares=chain-authelia@file
      - traefik.http.routers.bullboard.tls.certresolver=tlsresolver
      - traefik.http.routers.bullboard.service=bullboard
      - traefik.http.services.bullboard.loadbalancer.server.port=3007
    secrets:
      - redis_user
      - redis_password
    environment:
      REDIS_HOST: feedback-redis
      REDIS_DB: 0
      REDIS_USE_TLS: true
      REDIS_USER: /run/secrets/redis_user
      REDIS_PASSWORD: /run/secrets/redis_password

secrets:
  redis_user:
    file: ../secrets/redis_user
  redis_password:
    file: ../secrets/redis_password
