include:
  - ./infrastructure/traefik/compose.traefik.staging.yaml
  - ./infrastructure/postgres/compose.postgres.staging.yaml
  - ./infrastructure/minio/compose.minio.staging.yaml

services:
  feedback-server:
    container_name: feedback-server
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: staging-server
    # image: feedback-server
    develop:
      watch:
        - action: sync+restart
          path: ./apps/server/src
          target: /app/prod/server
    env_file:
      - ./apps/server/.env.staging
    restart: unless-stopped
    ports:
      - 3001:3001
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://$$SERVER_HOST:$$SERVER_PORT/healthcheck",
        ]
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.server-external.rule=Host(`api.localhost`) && (PathPrefix(`/docs`))"
      - "traefik.http.routers.server-external.entrypoints=web-secure"
      - "traefik.http.routers.server-external.tls=true"
      # - "traefik.http.routers.server-external.middlewares=chain-authelia@file"
      - "traefik.http.routers.server-external.service=server-external"
      - "traefik.http.services.server-external.loadbalancer.server.port=3001"

      - "traefik.http.routers.server-internal.rule=Host(`api.localhost`)"
      - "traefik.http.routers.server-internal.entrypoints=web-secure"
      - "traefik.http.routers.server-internal.tls=true"
      # - "traefik.http.routers.server-internal.middlewares=chain-no-auth@file"
      - "traefik.http.routers.server-internal.service=server-internal"
      - "traefik.http.services.server-internal.loadbalancer.server.port=3001"

  feedback-admin:
    container_name: feedback-admin
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: staging-admin
    env_file:
      - ./apps/admin/.env.staging
    image: feedback-admin
    develop:
      watch:
        - action: sync
          path: ./apps/admin/src
          target: /app/prod/admin/src
    ports:
      - 5174:5174
    depends_on:
      - feedback-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.localhost`)"
      - "traefik.http.routers.admin.entrypoints=web-secure"
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.services.admin.loadbalancer.server.port=5174"


  feedback-web:
    container_name: feedback-web
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      # args:
      #   VITE_API_BASE_URL: http://localhost:3001
      target: staging-web
    env_file:
      - ./apps/web/.env.staging
    image: feedback-web:latest
    develop:
      watch:
        - action: sync+restart
          path: ./apps/web/public
          target: /app/prod/web/public
        - action: sync
          path: ./apps/web/src
          target: /app/prod/web/src
        - action: sync+restart
          path: ./apps/web/index.html
          target: /app/prod/web/index.html
        - action: sync+restart
          path: ./apps/web/vite.config.ts
          target: /app/prod/web/vite.config.ts
        - action: rebuild
          path: ./apps/web/package.json
          target: /apps/prod/web/package.json
    ports:
      - 5173:5173
    restart: unless-stopped
    depends_on:
      - feedback-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.entrypoints=web-secure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.services.web.loadbalancer.server.port=5173"
