include:
  - ./infrastructure/compose.minio.local.yaml

services:
  feedback-server:
    container_name: feedback-server
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: dev-server
    image: feedback-server:latest
    develop:
      watch:
        - action: sync
          path: ./apps/server/src
          target: /app/prod/server
    env_file:
      - ./apps/server/.env
    restart: unless-stopped
    ports:
      - 3001:3001
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://$$SERVER_HOST:$$SERVER_PORT/healthcheck",
        ]

  feedback-workers:
    container_name: feedback-workers
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: prod-server
    command: "pnpm start:workers" 
    env_file:
      - ./apps/server/.env
    restart: unless-stopped
    depends_on:
      - feedback-server

  feedback-admin:
    container_name: feedback-admin
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      args:
        VITE_API_BASE_URL: http://localhost:3001
      target: dev-admin
    env_file:
      - ./apps/admin/.env
    develop:
      watch:
        - action: sync
          path: ./apps/admin/src
          target: /app/prod/admin/src
    ports:
      - 5174:5174
    depends_on:
      - feedback-server

  web:
    container_name: feedback-web
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: prod-web
    ports:
      - 5175:5175
    command: "pnpm dlx serve -p 5175"
    restart: unless-stopped
    depends_on:
      - feedback-server

secrets:
  minio_access_key:
    file: ./infrastructure/secrets/authelia_jwt_secret
  minio_secret_key:
    file: ./infrastructure/secrets/authelia_session_secret
  walg_libsodium_key:
    file: ./infrastructure/secrets/walg_libsodium_key
  postgres_user:
    file: ./infrastructure/secrets/postgres_user
  postgres_password:
    file: ./infrastructure/secrets/postgres_password
