include:
  - ./infrastructure/minio/compose.minio.local.yaml
  - ./infrastructure/redis/compose.redis.local.yaml

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile.bot
      target: prod-bot
    container_name: bot
    restart: unless-stopped
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: ./apps/bot
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    depends_on:
      - server

secrets:
  minio_access_key:
    file: ./infrastructure/secrets/authelia_jwt_secret
  minio_secret_key:
    file: ./infrastructure/secrets/authelia_session_secret
