include:
  - ./infrastructure/traefik/compose.traefik.staging.yaml
  - ./infrastructure/postgres/compose.postgres.staging.yaml
  - ./infrastructure/minio/compose.minio.staging.yaml

services:
  feedback-server:
    container_name: feedback-server
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      target: staging-server
    image: feedback-server:latest
    develop:
      watch:
        - action: sync
          path: ./apps/server/src
          target: /app/prod/server
    env_file:
      - ./apps/server/.env.staging
    restart: unless-stopped
    ports:
      - 3001:3001
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      test:
        [
          "CMD-SHELL",
          "wget --quiet --spider http://$$SERVER_HOST:$$SERVER_PORT/healthcheck",
        ]
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.server-external.rule=Host(`api.localhost`) && (PathPrefix(`/docs`))"
      - "traefik.http.routers.server-external.entrypoints=web-secure"
      - "traefik.http.routers.server-external.tls.certresolver=tlsresolver"
      # - "traefik.http.routers.server-external.middlewares=chain-authelia@file"
      - "traefik.http.routers.server-external.service=server-external"

      - "traefik.http.routers.server-internal.rule=Host(`api.localhost`)"
      - "traefik.http.routers.server-internal.entrypoints=web-secure"
      - "traefik.http.routers.server-internal.tls.certresolver=tlsresolver"
      # - "traefik.http.routers.server-internal.middlewares=chain-no-auth@file"
      - "traefik.http.routers.server-internal.service=server-internal"

      - "traefik.http.services.server-external.loadbalancer.server.port=3001"
      - "traefik.http.services.server-internal.loadbalancer.server.port=3001"

  feedback-admin:
    container_name: feedback-admin
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      # args:
      #   VITE_API_BASE_URL: http://localhost:3001
      target: staging-admin
    # env_file:
    #   - ./apps/admin/.env.staging
    image: feedback-admin:latest
    develop:
      watch:
        - action: sync
          path: ./apps/admin/src
          target: /app/prod/admin/src
    ports:
      - 5174:5174
    depends_on:
      - feedback-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.localhost`)"
      - "traefik.http.routers.admin.entrypoints=web-secure"
      - "traefik.http.routers.admin.tls.certresolver=tlsresolver"
      # - "traefik.http.routers.admin.middlewares=chain-no-auth@file"
      - "traefik.http.services.admin.loadbalancer.server.port=5174"


  feedback-web:
    container_name: feedback-web
    build:
      context: .
      dockerfile: ./Dockerfile.platform
      # args:
      #   VITE_API_BASE_URL: http://localhost:3001
      target: staging-web
    image: feedback-web:latest
    develop:
      watch:
        - action: sync
          path: ./apps/web/src
          target: /app/prod/web/src
    ports:
      - 5175:5175
    restart: unless-stopped
    depends_on:
      - feedback-server

secrets:
  minio_access_key:
    file: ./infrastructure/secrets/authelia_jwt_secret
  minio_secret_key:
    file: ./infrastructure/secrets/authelia_session_secret
