packages:
  - apps/*
  - shared/*

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true

catalog:
  '@biomejs/biome': 2.2.3
  '@dotenvx/dotenvx': 1.51.0
  '@hono/node-server': ^1.19.2
  '@orpc/client': ^1.12.3
  '@orpc/contract': ^1.12.3
  '@orpc/openapi': ^1.12.3
  '@orpc/openapi-client': ^1.12.3
  '@orpc/server': ^1.12.3
  '@orpc/valibot': ^1.12.3
  '@react-email/components': ^0.5.5
  '@react-email/preview-server': ^4.2.12
  '@refinedev/antd': ^6.0.3
  '@refinedev/cli': ^2.16.48
  '@refinedev/core': ^5.0.7
  '@refinedev/react-router': ^2.0.3
  '@types/node': ^22.10.0
  '@types/nodemailer': ^7.0.1
  '@types/pg': ^8.15.5
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  antd: ^5.27.4
  better-auth: ^1.4.7
  bullmq: ^5.58.9
  class-variance-authority: ^0.7.1
  globals: ^16.4.0
  hono: ^4.11.1
  ioredis: ^5.8.0
  kysely: ^0.28.9
  minio: ^8.0.6
  nodemailer: ^7.0.6
  oxlint: ^1.12.0
  pg: ^8.16.3
  pino: ^9.9.5
  pino-http: ^11.0.0
  pino-pretty: ^13.1.1
  react: ^19.1.1
  react-dom: ^19.1.1
  react-email: ^4.2.12
  react-router: ^7.9.1
  tsx: 4.20.5
  typescript: ^5.9.2
  valibot: ^1.1.0
  vite: ^7.1.5

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild

onlyBuiltDependencies:
  - esbuild

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'