packages:
  - apps/*
  - shared/*

catalog:
  '@biomejs/biome': ^2.3.10
  '@dotenvx/dotenvx': ^1.51.2
  '@hono/node-server': ^1.19.7
  '@orpc/client': ^1.13.0
  '@orpc/contract': ^1.13.0
  '@orpc/openapi': ^1.13.0
  '@orpc/openapi-client': ^1.13.0
  '@orpc/server': ^1.13.0
  '@orpc/valibot': ^1.13.0
  '@react-email/components': ^0.5.7
  '@react-email/preview-server': ^4.3.2
  '@refinedev/antd': ^6.0.3
  '@refinedev/cli': ^2.16.50
  '@refinedev/core': ^5.0.7
  '@refinedev/react-router': ^2.0.3
  '@types/node': ^22.19.3
  '@types/nodemailer': ^7.0.4
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.1.2
  antd: ^6.0.0
  better-auth: ^1.4.9
  class-variance-authority: ^0.7.1
  globals: ^16.4.0
  hono: ^4.11.1
  ioredis: ^5.8.0
  kysely: ^0.28.9
  minio: ^8.0.6
  nodemailer: ^7.0.12
  oxlint: ^1.35.0
  pg: ^8.16.3
  pino: ^9.14.0
  pino-http: ^11.0.0
  pino-pretty: ^13.1.3
  react: ^19.2.0
  react-dom: ^19.2.0
  react-email: ^4.3.2
  tsx: ^4.21.0
  typescript: ^5.9.3
  valibot: ^1.2.0
  vite: ^7.3.0

ignoredBuiltDependencies:
  - '@swc/core'
  - esbuild

onlyBuiltDependencies:
  - esbuild

overrides:
  brace-expansion@<=2.0.1: 2.0.2
  esbuild@<=0.24.2: '>=0.25.0'
  use-sync-external-store: ">=1.6.0"


syncInjectedDepsAfterScripts:
  - build
