services:
  feedback-redis:
    image: redis:8.4-alpine
    container_name: feedback-redis--development
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      REDIS_USER: mostsecretuser
      REDIS_PASSWORD: mostsecretpassword
    healthcheck:
      test:
        - CMD-SHELL
        - "redis-cli -a $${REDIS_PASSWORD} --sni --tls ping"
      interval: 15s
      timeout: 20s
      retries: 10
