services:
  feedback-redis:
    extends:
      file: compose.redis.development.yaml
      service: feedback-redis
    environment:
      REDIS_HOST: redis
      REDIS_USER: mostsecretuser
      REDIS_PASSWORD: mostsecretpassword
