services:
  redis:
    image: redis:8.2-alpine
    container_name: feedback-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--maxmemory-policy",
        "noeviction",
        "--save",
        "60",
        "1", 
        "--loglevel",
        "debug"
      ]
    healthcheck:
      test:
        - CMD-SHELL
        - "redis-cli -a $${REDIS_PASSWORD} --sni --tls ping"
      interval: 15s
      timeout: 20s
      retries: 10
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: mostsecretpassword
