services:
  feedback-minio:
    extends:
      file: compose.minio.development.yaml
      service: feedback-minio
    container_name: feedback-minio--production
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_secret_key
    secrets:
      - minio_access_key
      - minio_secret_key
    labels:
      - traefik.enable=true

      - traefik.http.routers.minio.entrypoints=web-secure
      - traefik.http.routers.minio.rule=Host(`minio.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)
      - traefik.http.routers.minio.tls.certresolver=tlsresolver
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

      - traefik.http.routers.minioweb.entrypoints=web-secure
      - traefik.http.routers.minioweb.rule=Host(`minioweb.xn--47-dlckcacbiv4afwllqms4x.xn--p1ai`)
      - traefik.http.routers.minioweb.middlewares=chain-authelia@file
      - traefik.http.routers.minioweb.tls.certresolver=tlsresolver
      - traefik.http.routers.minioweb.service=minioweb
      - traefik.http.services.minioweb.loadbalancer.server.port=9001

secrets:
  minio_access_key:
    file: ../secrets/minio_access_key
  minio_secret_key:
    file: ../secrets/minio_secret_key
