services:
  feedback-minio:
    extends:
      file: compose.minio.development.yaml
      service: feedback-minio
    container_name: feedback-minio--staging
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=web-secure
      - traefik.http.routers.minio.rule=Host(`minio.localhost`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

      - traefik.http.routers.minioweb.entrypoints=web-secure
      - traefik.http.routers.minioweb.rule=Host(`minioweb.localhost`)
      - traefik.http.routers.minioweb.tls=true
      - traefik.http.routers.minioweb.service=minioweb
      - traefik.http.services.minioweb.loadbalancer.server.port=9001
