services:
  feedback-minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: feedback-minio--development
    restart: unless-stopped
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: mostsecretminiokey
      MINIO_ROOT_PASSWORD: mostsecretminiokey