http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          - custom-fail2ban
          - middleware-rate-limit
          - middleware-secure-headers
          - middleware-authelia