services:
  minio:
    extends:
      file: compose.minio.local.yaml
      service: minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.entrypoints=web-secure
      - traefik.http.routers.minio.rule=Host(`minio.localhost`)
      - traefik.http.routers.minio.tls.certresolver=tlsresolver
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

      - traefik.http.routers.minioweb.entrypoints=web-secure
      - traefik.http.routers.minioweb.rule=Host(`minioweb.localhost`)
      - traefik.http.routers.minioweb.middlewares=chain-authelia@file
      - traefik.http.routers.minioweb.tls.certresolver=tlsresolver
      - traefik.http.routers.minioweb.service=minioweb
      - traefik.http.services.minioweb.loadbalancer.server.port=9001

volumes:
  minio-data:
